import type { Project } from "@/components/ProjectCard";

export const placeholderProjects: Project[] = [
  {
    _id: "1",
    client: "Echoes of Light",
    subtitle: "Short Film",
    slug: "echoes-of-light",
    category: ["selected", "narrative"],
    stillUrl: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=900&h=600&fit=crop",
    videoUrl: "",
    director: "James Liu",
  },
  {
    _id: "2",
    client: "Raveena",
    subtitle: "Midnight Bloom",
    slug: "midnight-bloom",
    category: ["selected", "music-video"],
    stillUrl: "https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?w=900&h=600&fit=crop",
    videoUrl: "",
    director: "Cara Stricker",
  },
  {
    _id: "3",
    client: "Mercedes-Benz",
    subtitle: "The Atlas Project",
    slug: "atlas-project",
    category: ["selected", "commercial"],
    stillUrl: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=900&h=600&fit=crop",
    videoUrl: "",
    director: "Daniel Sannwald",
  },
  {
    _id: "4",
    client: "SZA",
    subtitle: "Neon Dreams",
    slug: "neon-dreams",
    category: ["music-video"],
    stillUrl: "https://images.unsplash.com/photo-1524712245354-2c4e5e7121c0?w=900&h=600&fit=crop",
    videoUrl: "",
    director: "Bradley J. Calder",
  },
  {
    _id: "5",
    client: "Daniel Caesar",
    subtitle: "Hollow",
    slug: "hollow",
    category: ["music-video"],
    stillUrl: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=900&h=600&fit=crop",
    videoUrl: "",
    director: "Emily Kai Bock",
  },
  {
    _id: "6",
    client: "Kali Uchis",
    subtitle: "Golden Hour",
    slug: "golden-hour",
    category: ["music-video"],
    stillUrl: "https://images.unsplash.com/photo-1504275107627-0c2ba7a43dba?w=900&h=600&fit=crop",
    videoUrl: "",
    director: "Christine Yuan",
  },
  {
    _id: "7",
    client: "Nike",
    subtitle: "Origins",
    slug: "origins",
    category: ["commercial"],
    stillUrl: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=900&h=600&fit=crop",
    videoUrl: "",
    director: "Terrence Neal",
  },
  {
    _id: "8",
    client: "Adidas",
    subtitle: "Unleashed",
    slug: "unleashed",
    category: ["commercial"],
    stillUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=900&h=600&fit=crop",
    videoUrl: "",
    director: "Henry Scholfield",
  },
  {
    _id: "9",
    client: "Apple",
    subtitle: "Perspectives",
    slug: "perspectives",
    category: ["commercial"],
    stillUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=900&h=600&fit=crop",
    videoUrl: "",
    director: "Yann Demange",
  },
  {
    _id: "10",
    client: "The Last Station",
    subtitle: "Feature Film",
    slug: "last-station",
    category: ["narrative"],
    stillUrl: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=900&h=600&fit=crop",
    videoUrl: "",
    director: "Sofia Mendes",
  },
  {
    _id: "11",
    client: "Paper Walls",
    subtitle: "Short Film",
    slug: "paper-walls",
    category: ["narrative"],
    stillUrl: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=900&h=600&fit=crop",
    videoUrl: "",
    director: "Alex Rivera",
  },
  {
    _id: "12",
    client: "Silent Meridian",
    subtitle: "Documentary",
    slug: "silent-meridian",
    category: ["narrative"],
    stillUrl: "https://images.unsplash.com/photo-1518156677180-95a2893f3e9f?w=900&h=600&fit=crop",
    videoUrl: "",
    director: "Mara Osman",
  },
];
